# Generated by Django 3.1.1 on 2020-10-17 15:41

from django.db import migrations, models
import django.db.models.deletion
import galerie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0003_inscrit_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=galerie.models.photo_formation)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
    ]
