# Generated by Django 3.1.1 on 2020-10-17 17:55

from django.db import migrations, models
import django.db.models.deletion
import galerie.models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_inscrit_evenement'),
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie_Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=galerie.models.photo_evenement)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
            ],
        ),
    ]
