# Generated by Django 3.1.1 on 2020-11-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_auto_20201102_1316'),
        ('evenement', '0002_inscrit_evenement'),
        ('galerie', '0002_galerie_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie_evenement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='galerie_formation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation', verbose_name='formation'),
        ),
    ]
