# Generated by Django 3.1.1 on 2020-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='dateDeNais',
            field=models.DateField(verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Mâle'), ('FEMME', 'Femelle')], max_length=10, verbose_name='genre'),
        ),
    ]
