# Generated by Django 3.1.1 on 2020-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201025_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, verbose_name='genre'),
        ),
    ]
