# Generated by Django 3.1.1 on 2020-09-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('nom_en', models.CharField(max_length=20, null=True)),
                ('nom_fr', models.CharField(max_length=20, null=True)),
                ('nom_ar', models.CharField(max_length=20, null=True)),
                ('formation_type', models.CharField(choices=[('GOLD', 'Gold'), ('NORMAL', 'Normal')], max_length=20)),
                ('description', models.TextField(default=' ', max_length=1000)),
                ('description_en', models.TextField(default=' ', max_length=1000, null=True)),
                ('description_fr', models.TextField(default=' ', max_length=1000, null=True)),
                ('description_ar', models.TextField(default=' ', max_length=1000, null=True)),
                ('prix', models.IntegerField()),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_en_h', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.categorie')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveau')),
            ],
        ),
    ]
