# Generated by Django 3.1.1 on 2020-10-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('formation', '0002_formation_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrit_Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
            options={
                'unique_together': {('etudiant', 'formation')},
            },
        ),
    ]
