# Generated by Django 3.1.1 on 2020-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_inscrit_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(choices=[('GOLD', 'Or'), ('NORMAL', 'Normal')], max_length=20),
        ),
    ]
