# Generated by Django 3.1.1 on 2020-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_auto_20201025_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('NORMAL', 'Normal')], max_length=20),
        ),
    ]
