# Generated by Django 3.1.1 on 2020-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_auto_20201025_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(choices=[('OR', 'Or'), ('NORMAL', 'Normal')], max_length=20),
        ),
    ]
