# Generated by Django 3.1.1 on 2020-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_auto_20201101_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formation_type_ar',
            field=models.CharField(choices=[('OR', 'Or'), ('NORMAL', 'Normal')], max_length=20, null=True, verbose_name='Type de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_type_en',
            field=models.CharField(choices=[('OR', 'Or'), ('NORMAL', 'Normal')], max_length=20, null=True, verbose_name='Type de formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formation_type_fr',
            field=models.CharField(choices=[('OR', 'Or'), ('NORMAL', 'Normal')], max_length=20, null=True, verbose_name='Type de formation'),
        ),
    ]
