# Generated by Django 3.1.1 on 2020-11-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_auto_20201102_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='formation_type_ar',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='formation_type_en',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='formation_type_fr',
        ),
    ]
