# Generated by Django 3.1.1 on 2020-09-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(choices=[('premiere', 1), ('dexieme', 2), ('troisieme', 3), ('quatrieme', 4), ('cinqieme', 5)], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('nom_en', models.CharField(max_length=20, null=True, unique=True)),
                ('nom_fr', models.CharField(max_length=20, null=True, unique=True)),
                ('nom_ar', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau_scolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Prepremaire', 'Pre Primary'), ('Premaire', 'Primary'), ('Moyen', 'Middle'), ('Lycee', 'Secondary'), ('Universitaire', 'University')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('description', models.TextField(default=' ', max_length=1000)),
                ('description_en', models.TextField(default=' ', max_length=1000, null=True)),
                ('description_fr', models.TextField(default=' ', max_length=1000, null=True)),
                ('description_ar', models.TextField(default=' ', max_length=1000, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.annee')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.niveau_scolaire')),
            ],
            options={
                'unique_together': {('niveau', 'annee', 'matiere')},
            },
        ),
    ]
