# Generated by Django 3.1.1 on 2020-10-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cours', '0002_auto_20200927_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Inscrit_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
