# Generated by Django 3.1.1 on 2020-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_auto_20201011_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau_scolaire',
            name='nom',
            field=models.CharField(choices=[('Prepremaire', 'Pré primaire'), ('Premaire', 'Primaire'), ('Moyen', 'Moyen'), ('Lycee', 'Secondaire'), ('Universitaire', 'Université')], max_length=15, unique=True),
        ),
    ]
