# Generated by Django 3.1.1 on 2020-10-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_auto_20201025_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.annee', verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.matiere', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.niveau_scolaire', verbose_name='Niveau scolaire'),
        ),
    ]
