# Generated by Django 3.1.1 on 2020-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('titre_en', models.CharField(max_length=100, null=True)),
                ('titre_fr', models.CharField(max_length=100, null=True)),
                ('titre_ar', models.CharField(max_length=100, null=True)),
                ('lieu', models.CharField(max_length=100)),
                ('lieu_en', models.CharField(max_length=100, null=True)),
                ('lieu_fr', models.CharField(max_length=100, null=True)),
                ('lieu_ar', models.CharField(max_length=100, null=True)),
                ('date_et_heure', models.DateTimeField()),
                ('formatteur', models.CharField(max_length=30)),
                ('formatteur_en', models.CharField(max_length=30, null=True)),
                ('formatteur_fr', models.CharField(max_length=30, null=True)),
                ('formatteur_ar', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
