# Generated by Django 3.1.1 on 2020-10-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrit_evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
            ],
            options={
                'unique_together': {('etudiant', 'evenement')},
            },
        ),
    ]
